apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeoff
  labels:
    app: timeoff
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: timeoff
  template:
    metadata:
      labels:
        app: timeoff
    spec:
      containers:
      - name: alpine_timeoff
        image: 975050107562.dkr.ecr.us-east-1.amazonaws.com/timeoff
        ports:
        - containerPort: 3000  # Adjust the container port as needed
        resources:
          limits:
            cpu: "0.5"  # Adjust as needed
            memory: "512Mi"  # Adjust as needed

---
apiVersion: v1
kind: Service
metadata:
  name: timeoff-app-svc
spec:
  selector:
    app: timeoff-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
