apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeoff-app
  labels:
    app: timeoff-app
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: timeoff-app
  template:
    metadata:
      labels:
        app: timeoff-app
    spec:
      containers:
      - name: my-timeoff-app
        image: 975050107562.dkr.ecr.us-east-1.amazonaws.com/timeoff
        ports:
        - containerPort: 3000  # Adjust the container port as needed

---
apiVersion: v1
kind: Service
metadata:
  name: timeoff-app-svc
spec:
  selector:
    app: timeoff-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
