apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeoff-deployment
  labels:
    app: timeoff
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: timeoff
  template:
    metadata:
      labels:
        app: timeoff
    spec:
      containers:
      - name: timeoff-container
        image: 975050107562.dkr.ecr.us-east-1.amazonaws.com/timeoff-ecr-repo
        ports:
        - containerPort: 3000  # Adjust the container port as needed

---
apiVersion: v1
kind: Service
metadata:
  name: pimeoff-off-svc
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
